package misc.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static misc.Tarkistimet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.20 21:18:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkistimetTest {



  // Generated by ComTest BEGIN
  /** testOnkoPvm17 */
  @Test
  public void testOnkoPvm17() {    // Tarkistimet: 17
    assertEquals("From: Tarkistimet line: 18", true, onkoPvm("01.01.2019")); 
    assertEquals("From: Tarkistimet line: 19", true, onkoPvm("1.1.2019")); 
    assertEquals("From: Tarkistimet line: 20", true, onkoPvm("01.2.2020")); 
    assertEquals("From: Tarkistimet line: 21", true, onkoPvm("10. 10. 2020")); 
    assertEquals("From: Tarkistimet line: 22", false, onkoPvm("29.02.2019")); 
    assertEquals("From: Tarkistimet line: 23", true, onkoPvm("29.02.2020")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMuotoiltuPvm41 */
  @Test
  public void testMuotoiltuPvm41() {    // Tarkistimet: 41
    assertEquals("From: Tarkistimet line: 42", "02.03.2019", muotoiltuPvm("02.03.2019")); 
    assertEquals("From: Tarkistimet line: 43", "05.06.2020", muotoiltuPvm("5.6.2020")); 
    assertEquals("From: Tarkistimet line: 44", "20.01.2005", muotoiltuPvm("20.   1.      2005")); 
    assertEquals("From: Tarkistimet line: 45", "Merkkijonosta \"elokuun ensimmäinen torstai\" ei saatu parsittua päivämäärää!", muotoiltuPvm("elokuun ensimmäinen torstai")); 
  } // Generated by ComTest END
}