package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Scanner;
import java.io.FileInputStream;
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.20 14:30:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** testTallenna48 */
  @Test
  public void testTallenna48() {    // Joukkueet: 48
    File f = new File("./test/joukkueet.dat"); 
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue j1 = new Joukkue(); 
    Joukkue j2 = new Joukkue(); 
    j1.muokkaa("a", "b", "c", "d", 0); 
    j2.muokkaa("h", "i", "j", "k", 4); 
    j1.rekisteroi(); 
    j2.rekisteroi(); 
    joukkueet.lisaa(j1); 
    joukkueet.lisaa(j2); 
    try {
    joukkueet.tallenna("./test/joukkueet.dat"); 
    } catch (Exception e){
    }
    try(Scanner fi = new Scanner(new FileInputStream(f))){
    assertEquals("From: Joukkueet line: 74", "0|0|a|b|c|d", fi.nextLine()); 
    assertEquals("From: Joukkueet line: 75", "1|4|h|i|j|k", fi.nextLine()); 
    assertEquals("From: Joukkueet line: 76", false, fi.hasNext()); 
    } catch (Exception e) {
    }
    Joukkueet joukkueetLadattu = new Joukkueet(); 
    try{
    joukkueetLadattu.lataa("./test/joukkueet.dat"); 
    } catch (Exception e) {
    }
    assertEquals("From: Joukkueet line: 87", 2, joukkueetLadattu.getLkm()); 
    assertEquals("From: Joukkueet line: 88", 1, joukkueetLadattu.get(1).getJid()); 
    assertEquals("From: Joukkueet line: 89", "a", joukkueetLadattu.get(0).getNimi()); 
    f.delete(); 
  } // Generated by ComTest END
}