package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.20 13:42:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiigatTest {



  // Generated by ComTest BEGIN
  /** testLisaa79 */
  @Test
  public void testLisaa79() {    // Liigat: 79
    var liigat = new Liigat(); 
    var l1 = new Liiga(); 
    var l2 = new Liiga(); 
    l1.taytaLiiga(); 
    l2.taytaLiiga(); 
    liigat.lisaa(l1); 
    assertEquals("From: Liigat line: 86", 1, liigat.getLkm()); 
    liigat.lisaa(l2); 
    assertEquals("From: Liigat line: 88", 2, liigat.getLkm()); 
    assertEquals("From: Liigat line: 89", true, l1.getNimi() == l2.getNimi()); 
    l1.muokkaa("Kaljaliiga", 500, 10000, 2, 5000, 25000, 25); 
    assertEquals("From: Liigat line: 91", false, l1.getNimi() == l2.getNimi()); 
    liigat.poista(l1); 
    assertEquals("From: Liigat line: 93", true, liigat.get(0) == l2); 
    assertEquals("From: Liigat line: 94", 1, liigat.getLkm()); 
  } // Generated by ComTest END
}