package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.27 13:01:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiigatTest {



  // Generated by ComTest BEGIN
  /** testLisaa18 */
  @Test
  public void testLisaa18() {    // Liigat: 18
    var liigat = new Liigat(); 
    var l1 = new Liiga(); 
    var l2 = new Liiga(); 
    l1.taytaLiiga(); 
    l2.taytaLiiga(); 
    liigat.lisaa(l1); 
    assertEquals("From: Liigat line: 25", 1, liigat.getLkm()); 
    liigat.lisaa(l2); 
    assertEquals("From: Liigat line: 27", 2, liigat.getLkm()); 
    assertEquals("From: Liigat line: 28", true, l1.getNimi() == l2.getNimi()); 
    l1.muokkaa("Kaljaliiga", 500, 10000, 2, 5000, 25000, 25); 
    assertEquals("From: Liigat line: 30", false, l1.getNimi() == l2.getNimi()); 
  } // Generated by ComTest END
}