package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.27 01:34:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {
}