package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.27 10:54:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SopimusrekisteriTest {


  // Generated by ComTest BEGIN
  /** testMain79 */
  @Test
  public void testMain79() {    // Sopimusrekisteri: 79
    Sopimusrekisteri sr = new Sopimusrekisteri(); 
    Pelaaja p1 = new Pelaaja(); 
    Pelaaja p2 = new Pelaaja(); 
    p1.taytaPelaaja(); 
    p1.rekisteroi(); 
    p2.taytaPelaaja(); 
    p2.rekisteroi(); 
    sr.lisaa(p1); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    assertEquals("From: Sopimusrekisteri line: 96", "Doe", p1.getSukunimi()); 
    p1.muokkaa("Doge", "John", "647832", "Canada"); 
    assertEquals("From: Sopimusrekisteri line: 98", "Doge", p1.getSukunimi()); 
    assertEquals("From: Sopimusrekisteri line: 99", 9, sr.getPelaajia()); 
    sr.poista(p1); 
    assertEquals("From: Sopimusrekisteri line: 101", 8, sr.getPelaajia()); 
  } // Generated by ComTest END
}