package sopimusrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sopimusrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.27 19:38:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SopimusrekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa23 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa23() throws SailoException {    // Sopimusrekisteri: 23
    Sopimusrekisteri sr = new Sopimusrekisteri(); 
    Pelaaja p1 = new Pelaaja(); 
    Pelaaja p2 = new Pelaaja(); 
    p1.taytaPelaaja(); 
    p1.rekisteroi(); 
    p2.taytaPelaaja(); 
    p2.rekisteroi(); 
    sr.lisaa(p1); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    sr.lisaa(p2); 
    assertEquals("From: Sopimusrekisteri line: 41", "Doe", p1.getSukunimi()); 
    p1.muokkaa("Doge", "John", "647832", "Canada"); 
    assertEquals("From: Sopimusrekisteri line: 43", "Doge", p1.getSukunimi()); 
    assertEquals("From: Sopimusrekisteri line: 44", 9, sr.getPelaajia()); 
    sr.poista(p1); 
    assertEquals("From: Sopimusrekisteri line: 46", 8, sr.getPelaajia()); 
    Joukkue j1 = new Joukkue(); 
    Joukkue j2 = new Joukkue(); 
    j1.taytaJoukkue(); 
    j1.rekisteroi(); 
    j2.taytaJoukkue(); 
    j2.rekisteroi(); 
    sr.lisaa(j1); 
    sr.lisaa(j2); 
    assertEquals("From: Sopimusrekisteri line: 55", 2, sr.getJoukkueita()); 
    sr.poista(j1); 
    assertEquals("From: Sopimusrekisteri line: 57", j2, sr.getJoukkue(0)); 
    assertEquals("From: Sopimusrekisteri line: 58", 1, sr.getJoukkueita()); 
    j2.muokkaa("Kiakko", "Kouvola", "K. Kummola", "k.kummola@kmail.com", 0); 
    assertEquals("From: Sopimusrekisteri line: 60", "Kiakko", j2.getNimi()); 
    Liiga l1 = new Liiga(); 
    Liiga l2 = new Liiga(); 
    l1.taytaLiiga(); 
    l1.rekisteroi(); 
    l2.taytaLiiga(); 
    l2.rekisteroi(); 
    sr.lisaa(l1); 
    sr.lisaa(l2); 
    assertEquals("From: Sopimusrekisteri line: 69", true, sr.getJoukkueenLiiga(j2) == l1); 
    j2.muokkaa("Kiakko", "Kouvola", "K. Kummola", "k.kummola@kmail.com", 1); 
    assertEquals("From: Sopimusrekisteri line: 71", true, sr.getJoukkueenLiiga(j2) == l2); 
    assertEquals("From: Sopimusrekisteri line: 72", 2, sr.getLiigoja()); 
    sr.poista(l1); 
    assertEquals("From: Sopimusrekisteri line: 74", 1, sr.getLiigoja()); 
    assertEquals("From: Sopimusrekisteri line: 75", true, sr.getJoukkueenLiiga(j2) == l2); 
    assertEquals("From: Sopimusrekisteri line: 77", 1000000, sr.getPelaajanSopimus(p2).getPalkka()); 
    sr.poista(sr.getPelaajanSopimus(p2)); 
  } // Generated by ComTest END
}